type: release
name: bank_complete
version: 0.1
description: Bank Example; all services
ion: 0.0.1
apps:
  - name: directory
    version: 0.1
    processapp: [directory, ion.services.coi.directory_service, DirectoryService]

  - name: datastore
    description: Data store service
    version: 0.1
    processapp: [datastore, ion.services.coi.datastore_service, DataStoreService]

  - name: resource_registry
    description: Resource registry service
    version: 0.1
    processapp: [resource_registry, ion.services.coi.resource_registry_service, ResourceRegistryService]

  - name: trade
    version: 0.1
    processapp: [trade, examples.bank.trade_service, TradeService]

  - name: bank
    version: 0.1
    processapp: [bank, examples.bank.bank_service, BankService]

  - name: service_gateway
    version: 0.1
    processapp: [service_gateway, ion.services.coi.service_gateway_service, ServiceGatewayService]
