type: release
name: bank_complete
version: 0.1
description: Bank Example; all services
ion: 0.0.1
apps:
  - name: directory
    version: 0.1
    processapp: [directory, ion.services.coi.directory_service, DirectoryService]

  - name: datastore
    description: Data store service
    version: 0.1
    processapp: [datastore, ion.services.coi.datastore_service, DataStoreService]

  - name: resource_registry
    description: Resource registry service
    version: 0.1
    processapp: [resource_registry, ion.services.coi.resource_registry_service, ResourceRegistryService]

  - name: hello_resource
    version: 0.1
    processapp: [hello_resource, examples.hello.hello_resource_service, HelloResourceService]

