type: release
name: dm_deploy
version: 0.1
description: Data Management Services
ion: 0.0.1
apps:
  - name: directory
    version: 0.1
    processapp: [directory, ion.services.coi.directory_service, DirectoryService]

  - name: datastore
    description: Data store service
    version: 0.1
    processapp: [datastore, ion.services.coi.datastore_service, DataStoreService]

  - name: resource_registry
    description: Resource registry service
    version: 0.1
    processapp: [resource_registry, ion.services.coi.resource_registry_service, ResourceRegistryService]
            
  - name: pubsub_management
    version: 0.1
    processapp: [pubsub_management, ion.services.dm.distribution.pubsub_management_service, PubsubManagementService]

  - name: ingestion_management
    version: 0.1
    processapp: [ingestion_management, ion.services.dm.ingestion.ingestion_management_service, IngestionManagementService]

  - name: transform_management
    version: 0.1
    processapp: [transform_management, ion.services.dm.transformation.transform_management_service, TransformManagementService]

  - name: dataset_management
    version: 0.1
    processapp: [dataset_management, ion.services.dm.inventory.dataset_management_service, DatasetManagementService]

  - name: data_retriever
    version: 0.1
    processapp: [data_retriever, ion.services.dm.inventory.data_retriever_service, DataRetrieverService]

  - name: index_management
    version: 0.1
    processapp: [index_management, ion.services.dm.inventory.index_management_service, IndexManagementService]

#  - name: catalog_management
#    version: 0.1
#    processapp: [catalog_management, ion.services.dm.presentation.catalog_management_service, CatalogManagementService]

#  - name: discovery
#    version: 0.1
#    processapp: [discovery, ion.services.dm.presentation.discovery_service, DiscoveryService]

#  - name: preservation_management
#    version: 0.1
#    processapp: [preservation_management, ion.services.dm.preservation.preservation_management_service, PreservationManagementService]

