type: release
name: Release2Configuration SA services
version: 0.1
description: Release 2 SA integration test configuration
ion: 0.0.1
apps:

#  - name: datastore
#    description: Data store service
#    version: 0.1
#    processapp: [datastore, ion.services.coi.datastore_service, DataStoreService]
#    config:
#        type: CouchDB
#        forceClean: true

# COI services

  - name: resource_registry
    description: Resource registry service
    version: 0.1
    processapp: [resource_registry, ion.services.coi.resource_registry_service, ResourceRegistryService]
    config:
        resource_registry:
            persistent: true
            force_clean: true

# DM services

  - name: PubSubResource
    version: 0.1
    processapp: [pubsub_management, ion.services.dm.distribution.pubsub_management_service, PubsubManagementService]

  - name: transform_management_service
    version: 0.1
    processapp: [transform_management_service, ion.services.dm.transformation.transform_management_service, TransformManagementService]

# SA services

  - name: data_acquisition_management
    version: 0.1
    processapp: [data_acquisition_management, ion.services.sa.acquisition.data_acquisition_management_service, DataAcquisitionManagementService]

  - name: data_product_management
    version: 0.1
    processapp: [data_product_management, ion.services.sa.product.data_product_management_service, DataProductManagementService]

  - name: data_process_management
    version: 0.1
    processapp: [data_process_management, ion.services.sa.process.data_process_management_service, DataProcessManagementService]

  - name: instrument_management_service
    version: 0.1
    processapp: [instrument_management_service, ion.services.sa.instrument.instrument_management_service, InstrumentManagementService]

  - name: marine_facility_management_service
    version: 0.1
    processapp: [instrument_management_service, ion.services.sa.marine_facility.marine_facility_management_service, MarineFacilityManagementService]

    